### ISSUE TITLE
关于pytorch-Forkgan的参数

### ISSUE THREAD

**Issue by Charlesfracis** [LeungWaiHo/pytorch-ForkGAN#1]
Hi， 您好，

我在尝试在本地运行起您repo里的代码，但目前效果不是很好。

请问您是否能够提供一版能够得到较好结果的参数呢？

另外希望能得到您的联系方式，以方便之后的请教。

我的微信号是：sylgwzj
邮箱：15520730127@163.com

期望您的答复。

**Comment by LeungWaiHo** [comment]
> Hi， 您好，
> 
> 我在尝试在本地运行起您repo里的代码，但目前效果不是很好。
> 
> 请问您是否能够提供一版能够得到较好结果的参数呢？
> 
> 另外希望能得到您的联系方式，以方便之后的请教。
> 
> 我的微信号是：sylgwzj 邮箱：[15520730127@163.com](mailto:15520730127@163.com)
> 
> 期望您的答复。

您好，这个文档是我将CycleGAN的官方代码修改为ForkGAN的一个初步尝试，参数等细节未深入进行实验比对，也欢迎一起交流~

**Comment by Benjiemin1997** [comment]
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    visualizer.display_current_results(model.get_current_visuals(), epoch, save_result)
  File "/data2/zgg/ForkGAN/code/util/visualizer.py", line 138, in display_current_results
    padding=2, opts=dict(title=title + ' images'))
  File "/data2/zgg/anaconda3/envs/forkgan/lib/python3.6/site-packages/visdom/__init__.py", line 389, in wrapped_f
    return f(*args, **kwargs)
  File "/data2/zgg/anaconda3/envs/forkgan/lib/python3.6/site-packages/visdom/__init__.py", line 1292, in images
    height = int(tensor.shape[2] + 2 * padding)
IndexError: tuple index out of range
你好，我在训练的时候遇到这个问题，想请问一下是什么原因呢？dataset文件结构我是按照CycleGAN，看过您的代码，visualizer.py和CycleGAN中visualizer.py是一致的，但是为什么训练的时候就会报错呢？
